#!/usr/bin/sh

sxhkd &

wmname LG3D &

picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 30
bspc config pointer_motion_interval 100

bspc config focused_border_color        "#dddddd"
bspc config normal_border_color         "#dddddd"
bspc config presel_feedback_color       "#dddddd"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a com.google.AndroidStudio state=floating
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a krunner border=off
